Repository AY2425S1-CS2103T-F14B-2/tp, pull requests merged in 2024-10, with the labels that each got.

#22 Add use cases 1-12 in DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#29 docs: Update Maximus responsibilities
  docs/AboutUs.md
Labels: type.Documentation

#28 Fix project site CSS
  .gitignore
  docs/stylesheets/main.css
Labels: type.Bug, priority.Medium, type.Documentation

#33 Add Course class to model
  src/main/java/tahub/contacts/model/course/Course.java
  src/test/java/tahub/contacts/model/course/CourseTest.java
Labels: type.Task, priority.High

#37 Add more unit tests for Course class
  src/test/java/tahub/contacts/model/course/CourseTest.java
Labels: priority.High

#45 Add a Grading System
  src/main/java/seedu/address/model/GradingSystem.java
Labels: type.Enhancement, priority.Medium

#49 Add comment model
  docs/DeveloperGuide.md
  src/main/java/tahub/contacts/model/comment/Comment.java
  src/test/java/tahub/contacts/model/comment/CommentTest.java
Labels: priority.Medium

#51 Add new classes and testcases
  src/main/java/tahub/contacts/model/course/Course.java
  src/main/java/tahub/contacts/model/courseclass/CourseClass.java
  src/main/java/tahub/contacts/model/courseclass/recitation/Recitation.java
  src/main/java/tahub/contacts/model/courseclass/tutorial/Tutorial.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/test/java/tahub/contacts/model/recitation/RecitationTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
  src/test/java/tahub/contacts/model/tutorial/TutorialTest.java
Labels: priority.High

#56 Write Json adapter for course class, and UniqueCourseList
  src/main/java/tahub/contacts/model/course/Course.java
  src/main/java/tahub/contacts/model/course/UniqueCourseList.java
  src/main/java/tahub/contacts/model/course/exceptions/CourseNotFoundException.java
  src/main/java/tahub/contacts/model/course/exceptions/DuplicateCourseException.java
  src/main/java/tahub/contacts/storage/JsonAdaptedCourse.java
  src/test/java/tahub/contacts/model/course/CourseTest.java
  src/test/java/tahub/contacts/model/course/UniqueCourseListTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedCourseTest.java
Labels: priority.High

#66 Update Ui for v1.3
  src/main/java/tahub/contacts/ui/HelpWindow.java
  src/main/java/tahub/contacts/ui/PersonCard.java
  src/main/java/tahub/contacts/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#73 Update the grading system to deal with % grading
  src/main/java/seedu/address/model/GradingSystem.java
  src/main/java/tahub/contacts/model/grade/GradingSystem.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/test/java/tahub/contacts/model/grade/GradingSystemTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
Labels: priority.High

#68 Add Storage classes for Tut and Rec
  src/main/java/tahub/contacts/model/courseclass/CourseClass.java
  src/main/java/tahub/contacts/model/courseclass/recitation/Recitation.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/model/tutorial/Tutorial.java
  src/main/java/tahub/contacts/storage/JsonAdaptedTutorial.java
  src/test/java/tahub/contacts/model/recitation/RecitationTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
  src/test/java/tahub/contacts/model/tutorial/TutorialTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedTutorialTest.java
Labels: priority.High

#41 Improvements to Attendance Model
  src/main/java/tahub/contacts/model/course/Attendance.java
  src/main/java/tahub/contacts/model/course/AttendanceSession.java
  src/main/java/tahub/contacts/model/course/exceptions/AttendanceOperationException.java
  src/main/java/tahub/contacts/model/person/exceptions/PersonNotFoundException.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/storage/JsonAdaptedAttendance.java
  src/main/java/tahub/contacts/storage/JsonAdaptedAttendanceSession.java
  src/test/java/tahub/contacts/model/course/AttendanceSessionTest.java
  src/test/java/tahub/contacts/model/course/AttendanceTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedAttendanceSessionTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedAttendanceTest.java
  src/test/java/tahub/contacts/testutil/AttendanceExamples.java
  src/test/java/tahub/contacts/testutil/ScaBuilder.java
Labels: priority.Medium

#82 Add sca storage
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/model/tutorial/Tutorial.java
  src/main/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociation.java
  src/main/java/tahub/contacts/storage/JsonAdaptedTutorial.java
  src/test/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociationTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedTutorialTest.java
Labels: priority.High

#92 Add Storage to Grading System (second time)
  src/main/java/tahub/contacts/model/grade/Grade.java
  src/main/java/tahub/contacts/model/grade/GradingSystem.java
  src/main/java/tahub/contacts/storage/JsonAdaptedGrade.java
  src/main/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociation.java
  src/main/java/tahub/contacts/storage/JsonSerializableGradingSystem.java
  src/test/java/tahub/contacts/model/grade/GradeTest.java
  src/test/java/tahub/contacts/model/grade/GradingSystemTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedGradeTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociationTest.java
  src/test/java/tahub/contacts/storage/JsonSerializableGradingSystemTest.java
Labels: type.Enhancement, priority.High

#89 Add attendance to scastorage
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociation.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociationTest.java
  src/test/java/tahub/contacts/testutil/ScaBuilder.java
Labels: priority.Medium

#96 Add sca commands
  src/test/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociationTest.java
Labels: priority.High

#105 feat: person sca integration
  src/main/java/tahub/contacts/logic/Logic.java
  src/main/java/tahub/contacts/logic/LogicManager.java
  src/main/java/tahub/contacts/model/Model.java
  src/main/java/tahub/contacts/model/ModelManager.java
  src/main/java/tahub/contacts/model/person/Person.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationList.java
  src/test/java/tahub/contacts/logic/LogicManagerTest.java
  src/test/java/tahub/contacts/logic/commands/AddCommandTest.java
  src/test/java/tahub/contacts/logic/commands/CourseCommandTest.java
  src/test/java/tahub/contacts/model/ModelManagerTest.java
  src/test/java/tahub/contacts/model/person/PersonTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationListTest.java
Labels: priority.High

#109 Bunch of miscellaneous changes to SCA, Student, Course, Tutorial Structure
  src/main/java/tahub/contacts/logic/Messages.java
  src/main/java/tahub/contacts/logic/parser/CliSyntax.java
  src/main/java/tahub/contacts/logic/parser/ParserUtil.java
  src/main/java/tahub/contacts/model/course/Course.java
  src/main/java/tahub/contacts/model/person/Person.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationList.java
  src/main/java/tahub/contacts/model/studentcourseassociation/exceptions/ScaNotFoundException.java
  src/main/java/tahub/contacts/model/tutorial/Tutorial.java
  src/test/java/tahub/contacts/model/person/PersonTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationListTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
Labels: priority.High

#111 Add Attendance commands
  build.gradle
  src/main/java/tahub/contacts/logic/commands/attend/AttendAbsentCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendClearCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendPresentCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendRemoveCommand.java
  src/main/java/tahub/contacts/logic/parser/AddressBookParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendAbsentCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendClearCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendPresentCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendRemoveCommandParser.java
  src/main/java/tahub/contacts/storage/JsonAdaptedAttendanceSession.java
  src/test/java/tahub/contacts/logic/parser/ParserUtilTest.java
Labels: type.Story, priority.High

#113 Add enroll command
  src/main/java/tahub/contacts/logic/Messages.java
  src/main/java/tahub/contacts/logic/commands/DeleteCourseCommand.java
  src/main/java/tahub/contacts/logic/commands/EditCourseCommand.java
  src/main/java/tahub/contacts/logic/commands/EnrollCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendAbsentCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendClearCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendPresentCommand.java
  src/main/java/tahub/contacts/logic/commands/attend/AttendRemoveCommand.java
  src/main/java/tahub/contacts/logic/parser/AddressBookParser.java
  src/main/java/tahub/contacts/logic/parser/CliSyntax.java
  src/main/java/tahub/contacts/logic/parser/CourseCommandParser.java
  src/main/java/tahub/contacts/logic/parser/DeleteCourseCommandParser.java
  src/main/java/tahub/contacts/logic/parser/EditCourseCommandParser.java
  src/main/java/tahub/contacts/logic/parser/EnrollCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendAbsentCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendClearCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendPresentCommandParser.java
  src/main/java/tahub/contacts/logic/parser/attend/AttendRemoveCommandParser.java
  src/main/java/tahub/contacts/model/ModelManager.java
  src/main/java/tahub/contacts/model/course/Course.java
  src/main/java/tahub/contacts/model/course/UniqueCourseList.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationList.java
  src/main/java/tahub/contacts/storage/JsonSerializableStudentCourseAssociationList.java
  src/test/java/tahub/contacts/logic/LogicManagerTest.java
  src/test/java/tahub/contacts/logic/commands/CommandTestUtil.java
  src/test/java/tahub/contacts/model/ModelManagerTest.java
  src/test/java/tahub/contacts/model/course/CourseTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
Labels: priority.High

#120 Modify DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteCourseSequenceDiagram.puml
  docs/diagrams/EditCourseSequenceDiagram-Logic.puml
  docs/diagrams/EditCourseSequenceDiagram-Model.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation

#122 Modify course command words
  src/main/java/tahub/contacts/logic/commands/course/CourseAddCommand.java
  src/main/java/tahub/contacts/logic/commands/course/CourseDeleteCommand.java
  src/main/java/tahub/contacts/logic/commands/course/CourseEditCommand.java
  src/main/java/tahub/contacts/logic/parser/AddressBookParser.java
  src/main/java/tahub/contacts/logic/parser/course/CourseAddCommandParser.java
  src/main/java/tahub/contacts/logic/parser/course/CourseDeleteCommandParser.java
  src/main/java/tahub/contacts/logic/parser/course/CourseEditCommandParser.java
  src/test/java/tahub/contacts/logic/commands/course/CourseAddCommandTest.java
  src/test/java/tahub/contacts/logic/commands/course/CourseDeleteCommandTest.java
  src/test/java/tahub/contacts/logic/commands/course/CourseEditCommandTest.java
  src/test/java/tahub/contacts/logic/parser/AddressBookParserTest.java
  src/test/java/tahub/contacts/logic/parser/course/CourseAddCommandParserTest.java
  src/test/java/tahub/contacts/logic/parser/course/CourseDeleteCommandParserTest.java
  src/test/java/tahub/contacts/logic/parser/course/CourseEditCommandParserTest.java
  src/test/java/tahub/contacts/testutil/EditCourseDescriptorBuilder.java
Labels: priority.Medium
