Repository AY2425S1-CS2103T-F14B-2/tp, pull requests merged in 2024-09, with the labels that each got.

#3 Add boon hsuan info
  docs/images/flyingdonkeys.png
  docs/team/boonhsuan.md
Labels: priority.Low

#5 Update AboutUs (cbh)
  docs/AboutUs.md
  docs/team/boonhsuan.md
Labels: type.Story

#9 Add Zee info to AboutUs
  docs/AboutUs.md
  docs/team/zee.md
Labels: type.Documentation

#17 Add documentation (README.md)
  README.md
  docs/images/Ui.png
  docs/images/Ui_AB3.png
  docs/images/tahc-icon.png
  docs/images/tahc-icon_197px.png
  docs/images/tahc-icon_512px.png
  docs/images/tahc-logo.png
  docs/images/tahc-logo_400px.png
  docs/team/zee.md
Labels: priority.High, type.Documentation

#23 Add Maximus photo
  docs/AboutUs.md
  docs/images/miloaisdino.png
  docs/team/maximus.md
Labels: type.Documentation
