Repository AY2425S1-CS2103T-F14B-2/tp, pull requests merged in 2024-11, with the labels that each got.

#124 Update UI v1.5
  src/main/java/tahub/contacts/Main.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociation.java
  src/main/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationList.java
  src/main/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociation.java
  src/main/java/tahub/contacts/storage/JsonSerializableStudentCourseAssociationList.java
  src/main/java/tahub/contacts/ui/AttendanceListCell.java
  src/main/java/tahub/contacts/ui/AttendanceWindow.java
  src/main/java/tahub/contacts/ui/MainWindow.java
  src/main/java/tahub/contacts/ui/PersonCard.java
  src/main/java/tahub/contacts/ui/PersonListPanel.java
  src/main/resources/view/AttendanceWindow.css
  src/main/resources/view/AttendanceWindow.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationListTest.java
  src/test/java/tahub/contacts/model/studentcourseassociation/StudentCourseAssociationTest.java
  src/test/java/tahub/contacts/storage/JsonAdaptedStudentCourseAssociationTest.java
  src/test/java/tahub/contacts/testutil/ScaBuilder.java
Labels: priority.High

#132 update ug with sca commands
  docs/UserGuide.md
Labels: alpha-bug

#143 docs: correct UG for v1.5
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High

#149 add assertions to grading system test
  src/test/java/tahub/contacts/model/grade/GradingSystemTest.java
Labels: priority.Medium

#150 Update User Guide
  .markdownlint.jsonc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Documentation

#155 docs: person & course update
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CourseDeleteSequenceDiagram.puml
  docs/diagrams/CourseEditSequenceDiagram-Logic.puml
  docs/diagrams/CourseEditSequenceDiagram-Model.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/PersonDeleteSequenceDiagram.puml
Labels: priority.High, type.Documentation

#156 Update outdated commands in UG
  docs/UserGuide.md
Labels: priority.High

#228 Fix initial Attendance and Documentation related issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, type.Documentation

#227 Fix issues 1
  docs/UserGuide.md
  docs/img.png
  docs/img_1.png
  src/main/java/tahub/contacts/logic/commands/enrollment/EnrollCommand.java
  src/main/java/tahub/contacts/logic/commands/enrollment/UnenrollCommand.java
  src/main/java/tahub/contacts/logic/parser/AddressBookParser.java
  src/main/java/tahub/contacts/logic/parser/enrollment/EnrollCommandParser.java
  src/main/java/tahub/contacts/logic/parser/enrollment/UnenrollCommandParser.java
  src/test/java/tahub/contacts/model/person/AddressTest.java
Labels: priority.High, alpha-bug

#162 fix: course commands help and error message
  src/main/java/tahub/contacts/logic/commands/course/CourseAddCommand.java
  src/main/java/tahub/contacts/logic/commands/course/CourseDeleteCommand.java
  src/main/java/tahub/contacts/logic/commands/course/CourseEditCommand.java
Labels: priority.Low, severity.VeryLow, alpha-bug

#230 fix: User Guide (person, course)
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, alpha-bug

#233 User Guide Improvements
  docs/UserGuide.md
Labels: type.Documentation

#238 docs: person allow index future enhancement
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation, alpha-bug

#242 fix: UG course code
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#241 Fix/email
  src/main/java/tahub/contacts/model/person/Email.java
  src/test/java/tahub/contacts/model/person/EmailTest.java
Labels: priority.High, alpha-bug

#247 fix: UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation, alpha-bug

#250 immediate course deletion on command from all student cards
  src/main/java/tahub/contacts/model/ModelManager.java
  src/main/java/tahub/contacts/ui/MainWindow.java
  src/test/java/tahub/contacts/logic/commands/course/CoursePersonDeleteCommandTest.java
Labels: priority.High

#252 Update version number
  src/main/java/tahub/contacts/MainApp.java
Labels: type.Documentation
